mysql:
    host: 127.0.0.1
    user: root
    password: Arujit@17
    database: login
    raise_on_warnings : True

tcp:
    host: 127.0.0.1
    port: 10024

redis:
     host : 127.0.0.1
     port:  6379
     db : 0
    